# Evaluation Notebook

In [12]:
import numpy as np
import pandas as pd
from sklearn.metrics import (mean_absolute_error, root_mean_squared_error, r2_score, 
                             accuracy_score, classification_report, confusion_matrix)
from pathlib import Path


In [2]:
# Load predictions

rf_preds = pd.read_parquet('../preds/rf_preds.parquet')[['Hospital overall rating', 'predicted']]
xgb_preds = pd.read_parquet('../preds/xgb_preds.parquet')[['Hospital overall rating', 'predicted']]



In [ ]:
# Evaluation metrics on continuous predictions:

preds_to_eval = [rf_preds, xgb_preds]
model_names = ["RF", "XGB"]
target = 'Hospital overall rating'

for i, model in enumerate(preds_to_eval):
    model = model[[target, 'predicted']].dropna().copy()
    y_true, y_pred = model[target], model['predicted']
    rmse = root_mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print(f'{model_names[i]} Model\nRMSE: {rmse}\nMAE: {mae}\nR2: {r2}\n')

RF Model
RMSE: 0.8840774655796679
MAE: 0.7178908583516533
R2: 0.3555781631438617

XGB Model
RMSE: 0.8433152695638348
MAE: 0.672757178645006
R2: 0.41363298122840764



In [13]:
#Evaluation metrics on rounded/classified predictions

for i, model in enumerate(preds_to_eval):
    model = model[[target, 'predicted']].dropna().copy()
    y_true, y_pred = model[target], model['predicted'].round().clip(1,5).astype(int)
    rmse = root_mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)
    
    print(f'{model_names[i]} Model\nRMSE: {rmse}\nMAE: {mae}\nR2: {r2}')
    print(f"Accuracy: {acc}")
    print(confusion_matrix(y_true, y_pred))
    print(classification_report(y_true, y_pred))
    print()

RF Model
RMSE: 0.9250430789896097
MAE: 0.6577181208053692
R2: 0.29447318761358965
Accuracy: 0.436241610738255
[[  2  36  14   3   0]
 [  1  62  78   8   0]
 [  0  25 136  32   1]
 [  0   9  82  54   1]
 [  0   0  18  28   6]]
              precision    recall  f1-score   support

         1.0       0.67      0.04      0.07        55
         2.0       0.47      0.42      0.44       149
         3.0       0.41      0.70      0.52       194
         4.0       0.43      0.37      0.40       146
         5.0       0.75      0.12      0.20        52

    accuracy                           0.44       596
   macro avg       0.55      0.33      0.33       596
weighted avg       0.49      0.44      0.40       596


XGB Model
RMSE: 0.886134808778472
MAE: 0.62751677852349
R2: 0.35257539569247043
Accuracy: 0.44966442953020136
[[  8  33  13   1   0]
 [  3  64  73   9   0]
 [  0  29 116  47   2]
 [  0   6  66  70   4]
 [  0   0  14  28  10]]
              precision    recall  f1-score   support

   